# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2042c581cef3c4b6160b2add17601c4dfc49630cf1bf42647b024ba3ca2ab89c4f07aca06894ffea156f32a37670ef4e87df4ab370a81bc2d2548e200b80905e

test:
  secret_key_base: 99b553a5d43e86192806f1b96447d3563e66ab6ae981d95b2c422bf7f8b929e132969ae6321a8ce50fdfc9be1488b0e26599126e65accf763c55ec70d0400524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
